---
- hosts: localhost
  connection: local

  vars:
    swap_file: /swapfile
    swap_file_size: 8G
    # username
    # email
    # fullname

  roles:
    - nodesource.node

  tasks:

    - name: Add GPG key for Docker
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

    - name: Add Docker repository
      apt_repository:
          repo: deb https://apt.dockerproject.org/repo {{ ansible_lsb.id|lower }}-{{ ansible_lsb.codename}} main

    - name: Add GPG key for yarn
      apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg

    - name: Add yarn repository
      apt_repository: 
          repo: deb https://dl.yarnpkg.com/debian/ stable main
          filename: 'yarn'

    - name: "Install APT packages. NOTE: This step may take a while..."
      apt: pkg={{ item }} state=installed
      register: apt_install
      with_items:
        - git
        - mercurial
        - tmux
        - libjpeg-dev
        - libtiff5-dev
        - nginx
        - supervisor
        - ansible
        - python-pip
        - python3-pip
        - virtualenvwrapper
        - ruby-dev
        - python-dev
        - python3-dev
        - libperl-dev
        - libncurses5-dev
        - libpq-dev
        - libsqlite3-dev
        - llvm
        - automake
        - libbz2-dev
        - curl
        - libreadline6-dev
        - libxml2-dev
        - postgresql
        - htop
        - docker-engine
        - aptitude
        - yarn

    - name: "Upgrade all APT packages to the latest version. NOTE: This step may take a while..."
      apt:
          upgrade: dist
          update_cache: yes

    - name: Install npm role from Ansible Galaxy
      command: ansible-galaxy install nodesource.node --ignore-errors
      when: apt_install.changed

    - name: Install NPM
      npm: name=npm global=true state=latest
      when: apt_install.changed

    - name: Install latest versions of Python packages
      command: pip install --upgrade pip virtualenvwrapper

    - name: "Compile Vim from source: uninstall the existing vim first"
      apt: pkg={{ item }} state=absent
      with_items:
        - vim
        - vim-runtime
        - gvim
        - vim-tiny
        - vim-common
        - vim-gui-common

    - name: "Compile Vim from source: clone the latest Vim from GitHub"
      git: repo="https://github.com/vim/vim.git" dest="/tmp/vim-source" update=no

    - name: "Compile Vim from source: run configure"
      command: >
        ./configure --with-features=huge 
            --enable-multibyte 
            --enable-rubyinterp 
            --enable-python3interp 
            --enable-perlinterp 
            --enable-luainterp 
            --enable-cscope --prefix=/usr
      args:
        chdir: /tmp/vim-source

    - name: "Get Vim version"
      shell: grep define.*VIM_VERSION_NODOT /tmp/vim-source/src/version.h | grep 'vim[0-9]\+' -o
      register: vim_version

    - name: "Compile Vim from source: make. NOTE: This step may take a while..."
      command: make VIMRUNTIMEDIR="/usr/share/vim/{{ vim_version.stdout }}"
      args:
        chdir: /tmp/vim-source
        creates: /tmp/vim-source/src/vim

    - name: "Compile Vim from source: make install"
      command: make install
      args:
        chdir: /tmp/vim-source
        creates: /usr/local/bin/vim

    - name: "Compile Vim from source: symlink"
      file: src=/usr/bin/vim dest=/usr/bin/vi state=link

    - name: Create "docker" group
      group: name=docker
      register: docker_group

    - name: Restart docker server
      command: service docker restart
      when: docker_group.changed

    - name: Create the developer user
      user: name="{{ username }}" comment="{{ fullname }}" shell=/bin/bash groups="sudo,docker"

    - name: Create .ssh dir
      file: path=/home/{{ username }}/.ssh state=directory mode=0700 owner={{ username }} group={{ username }}

    - name: Copy files to dests home
      template: >
          src=./homedir/{{ item }}
          dest=/home/{{ username }}/.{{ item }}
          owner={{ username }}
          group={{ username }}
          mode=0644
      with_items:
        - bash_aliases
        - gitconfig
        - tmux.conf
        - vimrc
        - ssh/rc

    - name: Creade dir structure for .vim folder
      file: dest=/home/{{ username }}/.vim/bundle state=directory owner={{ username }} group={{ username }} mode=0755

    - name: Clone vundle
      git: repo="https://github.com/VundleVim/Vundle.vim.git" dest="/home/{{ username }}/.vim/bundle/Vundle.vim" update=no 
      become: yes
      become_user: "{{ username }}"

    - name: Install Vim plugins
      command: echo -e '\n\n\n\n\n' | vim +PluginInstall +qall
      become: yes
      become_user: "{{ username }}"

    - name: Remove .viminfo file
      file: path=/home/{{ username }}/.viminfo state=absent


    # SWAP FILE
    - name: Check if swap file exists
      stat: path="{{swap_file}}" get_md5=no get_checksum=no
      register: swap_file_check

    - name: Create swap file
      command: fallocate -l {{ swap_file_size }} {{ swap_file }}
      when: not swap_file_check.stat.exists

    - name: Change swap file permissions
      file: path="{{swap_file}}" owner=root group=root mode=0600

    - name: Format swap file
      command: "mkswap {{ swap_file }}"
      when: not swap_file_check.stat.exists

    - name: Write swap entry in fstab
      mount: name=none src="{{swap_file}}" fstype=swap state=present

    - name: Enable swap
      command: "swapon -a"
