---
- hosts: localhost
  connection: local

  vars:
    # username
    # email
    # fullname

  roles:
    - nodesource.node

  tasks:
    - name: Install APT packages
      apt: pkg={{ item }} state=installed
      register: apt_install
      with_items:
        - git
        - mercurial
        - tmux
        - libjpeg-dev
        - libtiff5-dev
        - nginx
        - supervisor
        - ansible
        - python-pip
        - python3-pip
        - virtualenvwrapper
        - ruby-dev
        - python-dev
        - python3-dev
        - libperl-dev
        - libncurses5-dev
        - libpq-dev
        - libsqlite3-dev
        - llvm
        - automake
        - libbz2-dev
        - curl
        - libreadline6-dev
        - libxml2-dev
        - postgresql
        - htop
        - docker.io

    - name: Install npm role from Ansible Galaxy
      command: ansible-galaxy install nodesource.node --ignore-errors
      when: apt_install.changed

    - name: Install NPM
      npm: name=npm global=true state=latest
      when: apt_install.changed

    - name: Install latest versions of Python packages
      command: pip install --upgrade pip virtualenvwrapper

    - name: "Compile Vim from source: uninstall the existing vim first"
      apt: pkg={{ item }} state=absent
      with_items:
        - vim
        - vim-runtime
        - gvim
        - vim-tiny
        - vim-common
        - vim-gui-common

    - name: "Compile Vim from source: clone the latest Vim from GitHub"
      git: repo="https://github.com/vim/vim.git" dest="/tmp/vim-source" update=no

    - name: "Compile Vim from source: run configure"
      command: >
        ./configure --with-features=huge 
            --enable-multibyte 
            --enable-rubyinterp 
            --enable-python3interp 
            --enable-perlinterp 
            --enable-luainterp 
            --enable-cscope --prefix=/usr
      args:
        chdir: /tmp/vim-source

    - name: "Compile Vim from source: make. NOTE: This step may take a while..."
      command: make VIMRUNTIMEDIR=/usr/share/vim/vim74
      args:
        chdir: /tmp/vim-source
        creates: /tmp/vim-source/src/vim

    - name: "Compile Vim from source: make install"
      command: make install
      args:
        chdir: /tmp/vim-source
        creates: /usr/local/bin/vim

    - name: "Compile Vim from source: symlink"
      file: src=/usr/bin/vim dest=/usr/bin/vi state=link

    - name: Create "docker" group
      group: name=docker
      register: docker_group

    - name: Restart docker server
      command: service docker restart
      when: docker_group.changed

    - name: Create the developer user
      user: name="{{ username }}" comment="{{ fullname }}" shell=/bin/bash groups="sudo,docker"

    - name: Copy files to dests home
      template: >
          src=./homedir/{{ item }}
          dest=/home/{{ username }}/.{{ item }}
          owner={{ username }}
          group={{ username }}
          mode=0644
      with_items:
        - bash_aliases
        - gitconfig
        - tmux.conf
        - vimrc
        - ssh/rc

    - name: Creade dir structure for .vim folder
      file: dest=/home/{{ username }}/.vim/bundle state=directory owner={{ username }} group={{ username }} mode=0755

    - name: Clone vundle
      git: repo="https://github.com/gmarik/Vundle.vim.git" dest="/home/{{ username }}/.vim/bundle/Vundle.vim" update=no 
      become_user: "{{ username }}"

    - name: Install Vim plugins
      command: vim +PluginInstall +qall
      become_user: "{{ username }}"
